### ISSUE TITLE
207-900(Remake)

### ISSUE THREAD

**Issue by ChuoSpecialRapid201** [Tintinfan/JPplusSet#100]
![Mato_207](https://user-images.githubusercontent.com/81485156/128169725-0eab924a-f0cf-411a-8644-d6f532eb58b1.png)

**Comment by Tintinfan** [comment]
Added to latest dev version.

**Comment by Tintinfan** [comment]
https://github.com/Tintinfan/JPplusSet/issues/49 main 207-900 series topic.
