### ISSUE TITLE
40 / 51 Series

### ISSUE THREAD

**Issue by Bamit-303** [Tintinfan/JPplusSet#103]
JGR Train 40 & 51 Series

![40 51_資料用](https://user-images.githubusercontent.com/76616738/133413268-b957f477-e78d-48fa-80c0-6f3c3da2d806.png)

**Comment by Bamit-303** [comment]
Fix
![40 51-1-4](https://user-images.githubusercontent.com/76616738/146902922-ea4780f6-2792-47c2-8e7f-a312a1ecce81.png)
![40 51-1-5](https://user-images.githubusercontent.com/76616738/146902926-f28014a4-1f7f-4017-aa8b-95a4d2d93e4c.png)
![40 51-1-6](https://user-images.githubusercontent.com/76616738/146902927-6e6c4dda-c82f-4eae-826e-adc42e5dd155.png)

**Comment by Bamit-303** [comment]
Fix

Standard
![40 51-1-1](https://user-images.githubusercontent.com/76616738/162726328-87c510ce-a905-4166-b7ce-e116c5e740df.png)
![40 51-1-2](https://user-images.githubusercontent.com/76616738/162726329-853296e8-6df8-4305-b662-37f0678e3cb6.png)
![40 51-1-3](https://user-images.githubusercontent.com/76616738/162726331-3a0ab654-b713-4207-a4be-7f342d97627b.png)
![40 51-1-4](https://user-images.githubusercontent.com/76616738/162726335-8b1d1163-9796-4326-a7ac-ca0605ccdfe8.png)
![40 51-1-5](https://user-images.githubusercontent.com/76616738/162726338-050678ca-4ed0-46a0-878c-c7fc68904d72.png)
![40 51-1-6](https://user-images.githubusercontent.com/76616738/162726340-92f1bc5b-7489-44f3-9b57-c0aff7a0d85b.png)
![40 51-1-7](https://user-images.githubusercontent.com/76616738/162726341-d511d1f7-3768-4569-bc2d-ae35ca41bab6.png)
![40 51-1-8](https://user-images.githubusercontent.com/76616738/162726347-f58a5cd2-2645-42cd-8410-e8fb90736cb4.png)
![40 51-1-9](https://user-images.githubusercontent.com/76616738/162726349-f86e74e5-532b-46b0-adb5-648b618fca6e.png)
![40 51-1-10](https://user-images.githubusercontent.com/76616738/162726352-eb8c55f4-ef70-4998-bd6b-1f3d101f8cfa.png)

**Comment by Bamit-303** [comment]
Fix 2

Standard
![40 51-1-1](https://user-images.githubusercontent.com/76616738/216823167-a4f057a5-72e3-4df7-b51b-f3b891ae49cc.png)
![40 51-1-2](https://user-images.githubusercontent.com/76616738/216823168-3835eecc-ec45-4edf-aaca-ba27f5b11a8c.png)
![40 51-1-3](https://user-images.githubusercontent.com/76616738/216823170-228061e7-0d86-4ada-ac90-f8409908e625.png)
![40 51-1-4](https://user-images.githubusercontent.com/76616738/216823171-a1c36237-fcc0-40a3-836a-f0a0d3425698.png)
![40 51-1-5](https://user-images.githubusercontent.com/76616738/216823174-43e45b17-811d-4a8f-9e45-c0255270f63b.png)
![40 51-1-6](https://user-images.githubusercontent.com/76616738/216823175-a0e1905e-5b31-4cd2-b4bb-b6dd14837c97.png)
![40 51-1-7](https://user-images.githubusercontent.com/76616738/216823176-4b81e0dd-c2b3-40cd-90a2-c0dee0dc6549.png)
![40 51-1-8](https://user-images.githubusercontent.com/76616738/216823177-a57740db-2c4c-404f-9b32-de38ccc51d85.png)
![40 51-1-9](https://user-images.githubusercontent.com/76616738/216823178-0bc3c031-a364-4660-a738-f2c44342a611.png)
![40 51-1-10](https://user-images.githubusercontent.com/76616738/216823179-84d42b15-72fb-4f4c-800f-b407022112eb.png)

**Comment by Tintinfan** [comment]
Closed for now, until there are more liveries.
