### ISSUE TITLE
Kiha 141/142/143

### ISSUE THREAD

**Issue by ChuoSpecialRapid201** [Tintinfan/JPplusSet#107]
![k143](https://user-images.githubusercontent.com/81485156/142708734-f94e28b5-2137-4791-8913-16ed3f272d8c.png)
Kiha 143/Kisaha 144
(1994~)

![k141_2](https://user-images.githubusercontent.com/81485156/142707091-46c43703-3430-4e9c-a910-c524edcaf209.png)
Kiha 141/142(Blue Stripe)
(1995~)

![k141_2_g](https://user-images.githubusercontent.com/81485156/142707250-2f13c9f3-8a72-4b43-a98b-98e56ea7165f.png)
Kiha 141/142(Green Stripe)
(1990~)

**Comment by Tintinfan** [comment]
KiHa 141/142
--Livery Variation
KiHa 143


For KiHa 141/142 types, they graphic is dependent on the direction of the unit.
<- KiHa 141
-> KiHa 142

**Comment by Tintinfan** [comment]
Completed
