### ISSUE TITLE
8000 Series

### ISSUE THREAD

**Issue by cacapo2501** [Tintinfan/JPplusSet#108]
Original Color is complete.
![8000-1-1](https://user-images.githubusercontent.com/10273837/142776017-0b2e864c-a024-44cc-b5d5-9d0d7071b6b6.png)
![8000-1-2](https://user-images.githubusercontent.com/10273837/142776018-1af7503c-923a-476e-af30-142eb4217b89.png)
![8000-1-3](https://user-images.githubusercontent.com/10273837/142776019-10eb6fba-1394-4a36-8ce1-cdfd96a68fa4.png)
![8000-1-4](https://user-images.githubusercontent.com/10273837/142776020-bac0d688-78d3-4c31-8a2c-42f25da37f3a.png)
![8000-1-5](https://user-images.githubusercontent.com/10273837/142776021-f0f8e323-e424-4719-a95d-7372a4aa52c2.png)
![8000-1-6](https://user-images.githubusercontent.com/10273837/142776023-1cfcdf20-1bf9-46a3-83e0-fea482e9624e.png)
![8000-1-7](https://user-images.githubusercontent.com/10273837/142776024-e17503ee-e0ac-4b52-95e1-0abdecfc12d1.png)
![8000-1-8](https://user-images.githubusercontent.com/10273837/142776025-1cc49849-9d70-42b4-914e-a4bf14ec9ef5.png)
![purchase_32bpp](https://user-images.githubusercontent.com/10273837/142776026-0f2b2707-51cd-45b7-867a-5473bd357b3b.png)

**Comment by cacapo2501** [comment]
Original Colors are modified
![8000-1-1](https://user-images.githubusercontent.com/10273837/142928451-ff550975-9bc8-4de4-8c83-4372d7be8702.png)
![8000-1-2](https://user-images.githubusercontent.com/10273837/142928454-63b099d4-148e-4ccd-bd87-4abfc94223eb.png)
![8000-1-3](https://user-images.githubusercontent.com/10273837/142928457-4467041c-191a-42a1-9066-2c91e8d3b364.png)
![8000-1-4](https://user-images.githubusercontent.com/10273837/142928459-3cd34b13-1246-47b0-a167-353b5c66c652.png)
![8000-1-5](https://user-images.githubusercontent.com/10273837/142928461-2928f758-f958-4979-95d5-ebf0fe7e6f54.png)
![8000-1-6](https://user-images.githubusercontent.com/10273837/142928463-8872d849-efd4-427a-8ea7-ba5f1a235a88.png)
![8000-1-7](https://user-images.githubusercontent.com/10273837/142928466-d94709ea-5a9a-4dfe-8ff8-75fa6f3eb1a9.png)
![8000-1-8](https://user-images.githubusercontent.com/10273837/142928468-0ff731b0-aa58-43a1-beb7-44315bed7d4c.png)

**Comment by cacapo2501** [comment]
Renewal Colors are complete.
![8000-2-1](https://user-images.githubusercontent.com/10273837/142928504-9372d699-1209-4c14-9389-23d0f1a39401.png)
![8000-2-2](https://user-images.githubusercontent.com/10273837/142928505-87a1fdaa-495f-45d8-9402-fe0c391533f6.png)
![8000-2-3](https://user-images.githubusercontent.com/10273837/142928506-2b501a0f-4b08-41c0-91db-ffa0ddb08ea0.png)
![8000-2-4](https://user-images.githubusercontent.com/10273837/142928511-8586a0b7-ec4f-4c7e-ae67-94395b8c555c.png)
![8000-2-5](https://user-images.githubusercontent.com/10273837/142928512-67d15c97-c01f-4d95-8753-f82412b4866a.png)
![8000-2-6](https://user-images.githubusercontent.com/10273837/142928513-6f72ec20-f233-47eb-ba4e-21ee06f0b481.png)
![8000-2-7](https://user-images.githubusercontent.com/10273837/142928514-a65c3f17-c574-4164-988c-8a3470f30897.png)
![8000-2-8](https://user-images.githubusercontent.com/10273837/142928516-3d29c4c1-4b52-4547-b838-968c175fefb8.png)
![8000-2-9](https://user-images.githubusercontent.com/10273837/142928518-c4920b22-344b-45c2-8300-3294984f9242.png)

**Comment by cacapo2501** [comment]
8000_series.pnml is complete.
Adding following words for lang/english.lng
JRS_8000 : name of 8000 series
JRS_8000_DESC : Description for 8000 series
JRS8000_LV_ORIGINAL : Original Livery
JRS8000_LV_RENEWAL : Renewal Livery
[8000_series.zip](https://github.com/Tintinfan/JPplusSet/files/7584062/8000_series.zip)

**Comment by Tintinfan** [comment]
Modified to use the standard livery strings to use less string space;


LV_INITIAL: {PUSH_COLOUR}{WHITE}•{POP_COLOUR} Initial Livery
LV_RENEWAL: {PUSH_COLOUR}{WHITE}•{POP_COLOUR} Renewal Livery

**Comment by cacapo2501** [comment]
Thank you for modifying. I have no problem for your modifying.
