### ISSUE TITLE
207-900 Series (Re_Remake)

### ISSUE THREAD

**Issue by ChuoSpecialRapid201** [Tintinfan/JPplusSet#111]
![mato_207](https://user-images.githubusercontent.com/81485156/145670668-0fde6b37-7569-4555-bde6-6d7614e49d97.png)

**Comment by Tintinfan** [comment]
![207](https://github.com/Tintinfan/JPplusSet/assets/1836032/4163a084-b028-4c60-84e1-e99485d53efb)

+Transparent 32bpp
+Fake pantograph cars for 2car

Please use this for future updates!

Updated as of https://github.com/Tintinfan/JPplusSet/commit/d56973e0f1971c6fc8c48e23a9900959b34ab275
