### ISSUE TITLE
Kiha 58(Remake)

### ISSUE THREAD

**Issue by ChuoSpecialRapid201** [Tintinfan/JPplusSet#121]
![k58_jnr](https://user-images.githubusercontent.com/81485156/162617707-15c52acb-5578-4331-91a5-e04fdcd93c83.png)

Kiha 58/28 Seperated,
Added No-AC

**Comment by ChuoSpecialRapid201** [comment]
<img width="88" alt="k58_jnrr" src="https://github.com/Tintinfan/JPplusSet/assets/81485156/77a8469a-9198-4ecf-b5c6-e8706a24b357">
Re_Remake

**Comment by Tintinfan** [comment]
> <img alt="k58_jnrr" width="88" src="https://private-user-images.githubusercontent.com/81485156/274811722-8429383d-a57e-4539-9da5-427dbcf2fbf9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcwNjA0NjcsIm5iZiI6MTcwNzA2MDE2NywicGF0aCI6Ii84MTQ4NTE1Ni8yNzQ4MTE3MjItODQyOTM4M2QtYTU3ZS00NTM5LTlkYTUtNDI3ZGJjZjJmYmY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA0VDE1MjI0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE0MjY3NzFhYzNkMzQ2YTljZjI0YmY4ODg4NDgyODI5MDViNWE5MThmMTQzMTY2N2FhYTIwMTE5YTc3ZTg3MjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pkdOqtTL9jYdp5KBpfCzdz4lJsfGpXAy5NA11gE2U2o">
> 
> Re_Remake
![kh58remakefix](https://github.com/Tintinfan/JPplusSet/assets/1836032/e0725d07-646e-43e3-bfce-ad194d4c8892)

Made transparent; preperation for replacement

**Comment by Tintinfan** [comment]
Updated to Oct 13 2023 version as of https://github.com/Tintinfan/JPplusSet/commit/cf5f07b46f9fb395bf08007761e6b9b42ab829df
