### ISSUE TITLE
JR West 271, 281 series

### ISSUE THREAD

**Issue by Yozora3** [Tintinfan/JPplusSet#132]
271 series
![jrw_271](https://github.com/Tintinfan/JPplusSet/assets/96115762/149356bf-7620-4813-ae2c-7c3e74bf6193)

281 series
![JRW_281](https://github.com/Tintinfan/JPplusSet/assets/96115762/656d2393-c32d-471a-affc-16e87bc5801e)

**Comment by Tintinfan** [comment]
Done as of #384eec7
