### ISSUE TITLE
JR Central 315 series

### ISSUE THREAD

**Issue by Yozora3** [Tintinfan/JPplusSet#133]
![jrc_315series](https://github.com/Tintinfan/JPplusSet/assets/96115762/351f5c8e-5183-4fb3-a1f8-f1b8dc66beb9)

**Comment by Tintinfan** [comment]
Completed as of https://github.com/Tintinfan/JPplusSet/commit/f87b86d3891dbbc40f4b94c9a03360e51b00689b
