### ISSUE TITLE
52 Series EMU

### ISSUE THREAD

**Issue by EmperorJake** [Tintinfan/JPplusSet#139]
52 series in 9 liveries. 

Suggested consists: 
JGR Brown and JGR Cream: Normal trailer + trailer with 2nd class compartment
If it has a flat fronted trailer that trailer should only show in 2 car consists. Optionally the trailer can appear as the first car in a longer consist too, but maybe avoid this to keep things simple. 
Shonan livery should alternate between standard and modernised trailer
Suka should be split into 2 refits: standard trailer and 3-door modernised trailer

JGR Brown (1936)
![52_jgr_brown](https://github.com/Tintinfan/JPplusSet/assets/68182631/d227571c-b05f-4383-bb58-12f6a1313583)

JGR Cream/Brown 2nd Batch (1937)
![52_jgr_cream](https://github.com/Tintinfan/JPplusSet/assets/68182631/c540afaa-f82d-44dd-b8b0-3ae88d180d0d)

JGR Brown Wartime (1941)
![52_brown](https://github.com/Tintinfan/JPplusSet/assets/68182631/60416ce7-51b1-47cc-908f-34479f2d77ab)

JNR Kansai Rapid "Popsicle Colour" (1949)
![52_kansai_blue](https://github.com/Tintinfan/JPplusSet/assets/68182631/3d614f1d-8510-4115-b6d2-35cbec2a7033)

JNR Kansai/Hanwa Rapid "Popsicle Colour" (1949)
![52_kansai_stripe](https://github.com/Tintinfan/JPplusSet/assets/68182631/bb1b3298-6e9e-4ec4-82ec-7cf94b18da67)

JNR Hanwa Rapid Brown/Cream (1950)
![52_hanwa](https://github.com/Tintinfan/JPplusSet/assets/68182631/aa1376d7-ff48-4704-9e1c-31f221ca7a56)

JNR Iida Line Rapid "Shizutetsu" (1957)
![52_shizutetsu](https://github.com/Tintinfan/JPplusSet/assets/68182631/9d5862bb-8df7-4487-a548-0e7a51414765)

JNR Iida Line "Shonan" 
![52_shonan](https://github.com/Tintinfan/JPplusSet/assets/68182631/007266c4-b5fe-4550-95d7-0ea12c3b38ef)

JNR Iida Line "Yokosuka"
![52_suka](https://github.com/Tintinfan/JPplusSet/assets/68182631/f83e283c-c8d3-4f4a-8e38-c912b0404ab2)

**Comment by Tintinfan** [comment]
Finished with commit #6bed55b

**Comment by Tintinfan** [comment]
Finished with commit d4328b9
