### ISSUE TITLE
JR East E257 series

### ISSUE THREAD

**Issue by Yozora3** [Tintinfan/JPplusSet#141]
**0台**
Numeration: top->bottom 
![e257_0](https://github.com/Tintinfan/JPplusSet/assets/96115762/f721fa0b-dc40-4008-8506-e57cb1006ebe)

**500台**
Numeration: top->bottom 
![e257_500](https://github.com/Tintinfan/JPplusSet/assets/96115762/7093a465-f8a6-4601-bb68-2c99cbc9254c)

**2000＆2500台**
![e257_2000](https://github.com/Tintinfan/JPplusSet/assets/96115762/245e4054-c245-4988-a333-ed9b77cb6534)

**5000＆550
![e257_5000](https://github.com/Tintinfan/JPplusSet/assets/96115762/3eb10d1f-5621-411b-9174-69b9f67d6dd1)

Although I've added car numbers, be sure to double-check

**Comment by Yozora3** [comment]
0/2000/5000 updated

**Comment by Tintinfan** [comment]
Complete by commit https://github.com/Tintinfan/JPplusSet/commit/ed1628f7429117a2d0f2c33c063b69aa2347b66a
