### ISSUE TITLE
Bug JR 271 series and JR 281 series

### ISSUE THREAD

**Issue by RyuuElianor** [Tintinfan/JPplusSet#145]
**Describe the bug:**
Please describe the bug/issue. 

1. What is the bug/issue?

please fix it because there are bugs on both trains, namely the JR 271 series and JR 281 series, if only two trains are used, the train has no power or doesn't move at all, if you add carriage 4 If I turn the passenger carriage backwards, the train lane slows down 2KM/H, please fix this, this really disturbs the game.

**Screenshots:**
Please add screenshots to help describe the issue.

![Screenshot_20240510_050855](https://github.com/Tintinfan/JPplusSet/assets/169399124/e6baf36b-ac73-4ec0-a10d-6d5be64a1fa3)

**OpenTTD version:**
Please put the version of OpenTTD you are using here. OpenTTD 14.0 android

**Comment by Tintinfan** [comment]
Resolved issue, problem is unique to vanilla versions. Will be fixed next release.
