### ISSUE TITLE
213 Series Livery Selection Bug

### ISSUE THREAD

**Issue by KeepinItRail** [Tintinfan/JPplusSet#146]
**Describe the bug:**
Selecting alternative 213 Series Liveries does not change all cars

1. What is the bug/issue?
Selecting alternative 213 Series Liveries does not change all cars
2. How did you make the bug/issue happen? 
- Build a 6 car 213 Series
- Select a different livery (e.g. Shonan Livery or Marine Liner) and either only the front or both cans change.

3. What would fix the bug? 
Code fix

**Screenshots:**
![Screenshot from 2024-05-13 06-14-43](https://github.com/Tintinfan/JPplusSet/assets/74462886/fe24e4af-9353-4a94-98b2-e11135c5286c)

**OpenTTD version:**
JGRPP 0.59.0

**Comment by Tintinfan** [comment]
I believe that this is because the only 3 car 213 series were JR West - the refits for all appear as they should except for Shonan, which doesnt have a mid car sprite provided...can rectify this however.
