### ISSUE TITLE
113系 Yokosuka Livery

### ISSUE THREAD

**Issue by ChuoSpecialRapid201** [Tintinfan/JPplusSet#19]
![113-Suka-1](https://user-images.githubusercontent.com/81485156/124908652-833a1b80-e024-11eb-804b-b5cd12ab95d3.png)
Kuha 111

![113-Suka-2](https://user-images.githubusercontent.com/81485156/124908658-8503df00-e024-11eb-8626-767e0d54b3ca.png)
Moha 112/Saha 111

![113-Suka-3](https://user-images.githubusercontent.com/81485156/124908660-859c7580-e024-11eb-8d78-cfc308800917.png)
Moha 113

![113-Suka-4](https://user-images.githubusercontent.com/81485156/124908661-859c7580-e024-11eb-820f-dc15bcb4edfa.png)
Saro 110/111

![113-Suka-5](https://user-images.githubusercontent.com/81485156/124908662-86350c00-e024-11eb-951a-87e27136006e.png)
Saro 124/125

Ex,
![113sukaexp](https://user-images.githubusercontent.com/81485156/124912157-94852700-e028-11eb-8178-ac30e639e1c4.png)

**Comment by Tintinfan** [comment]
Moved to #34
