### ISSUE TITLE
581/583 Series

### ISSUE THREAD

**Issue by Bamit-303** [Tintinfan/JPplusSet#26]
![583_資料用](https://user-images.githubusercontent.com/76616738/138562706-8fab0e2f-1810-469d-8061-0a80784de29e.png)

**Comment by Bamit-303** [comment]
JNR Livery
581
![581-1-1](https://user-images.githubusercontent.com/76616738/145675540-1e9ef0ec-fa53-40ed-9fa8-13ebbc62c7b8.png)

583
![583-1-1](https://user-images.githubusercontent.com/76616738/145675543-027bb243-f992-4a6b-be15-0ba4b3efe689.png)
![583-1-2](https://user-images.githubusercontent.com/76616738/145675544-ef974522-9415-449d-a3f5-4ee96999974c.png)
![583-1-3](https://user-images.githubusercontent.com/76616738/145675546-e76f7a45-e9ad-4e76-a62e-fea262880af5.png)
![583-1-4](https://user-images.githubusercontent.com/76616738/145675547-daa0ab22-12cf-404e-a604-1b228509b012.png)
![583-1-5](https://user-images.githubusercontent.com/76616738/145675548-2d399769-a86f-47ed-b6f9-59928b420971.png)
![583-1-6](https://user-images.githubusercontent.com/76616738/145675549-10dab34c-068e-4b83-b712-3afb6d8f78ef.png)

**Comment by Tintinfan** [comment]
Added as of https://github.com/Tintinfan/JPplusSet/commit/7d9caf8889c6627d08e13cdc1207851de30f8a5f

Missing;
- Kitaguni Old Colour 1992-1996
- Kitaguni New Colour (JRW)
+ Formations Customisation
