### ISSUE TITLE
207-900 Series

### ISSUE THREAD

**Issue by ChuoSpecialRapid201** [Tintinfan/JPplusSet#49]
![207_900](https://user-images.githubusercontent.com/81485156/125166143-321d5980-e1d5-11eb-86be-c71497509e09.png)
-207系 900番台
Joban Line(Local)/Eidan Chiyoda Line

Ex)
![matoex](https://user-images.githubusercontent.com/81485156/124957344-f0b17080-e053-11eb-8494-dbf1ca3a8b34.png)
207系 900番台(Joban Line(Local)/Eidan Chiyoda Line)

**Comment by Tintinfan** [comment]
Hi,

I think @Bamit-303 said there is no top green stripe. Also please provide the sprite in a template with transparency (see attached example file). When you are done we can label it as "GFX: complete" and I can send it to be coded. :)

![209-500_keto_32bpp](https://user-images.githubusercontent.com/1836032/124955890-5596a780-e00f-11eb-8ce4-2269b37eb6c7.png)

**Comment by ChuoSpecialRapid201** [comment]
![207_900](https://user-images.githubusercontent.com/81485156/125036222-ba183c00-e0cd-11eb-8e40-d3e49f3567a2.png)
*graphic error fixed!

**Comment by Tintinfan** [comment]
https://github.com/Tintinfan/JPplusSet/issues/100 new graphics
